apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-read

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-read
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-account-rolebinding
subjects:
  - kind: ServiceAccount
    name: sa-read
roleRef:
  kind: Role
  name: role-read
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Pod
metadata:
  name: kubepod
spec:
  serviceAccountName: sa-read
  containers:
    - name: kubectl
      image: bitnami/kubectl
      command: ["sh", "-c"]
      args:
        - |
          while true
          do
            kubectl get pod
            sleep 30
          done
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
