apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1
spec:
  selector:
    matchLabels:
      run: nginx1
  replicas: 2
  template:
    metadata:
      labels:
        run: nginx1
    spec:
      containers:
        - name: nginx1
          image: nginx
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx1
  labels:
    run: nginx1
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    run: nginx1
